language: node_js
node_js:
  - 6
before_script:
  - sudo apt-get install build-essential libssl-dev git
  - git clone https://github.com/wg/wrk.git
  - cd wrk && make && sudo cp wrk /usr/local/bin && cd ..
script:
  - npm run test
  - npm run bench
after_script:
  - npm install codecov
  - ./node_modules/.bin/codecov
